### ISSUE TITLE
Perform zero-downtime redeploy also in dev

### ISSUE THREAD

**Issue by herder** [cloudcaptainsh/cloudcaptain#105]
Currently, boxfuse deploys a new instance of an app when i do `boxfuse run` in the `dev` environment.

I think it's probably better to do the same in `dev` as in the aws environments and pull up the new instance, check health, and then pull down the old instance. Besides mirroring the prod/stage environments' behaviour better, it would also allow us to have a known port for each local app, which would simplify integration between apps and possibly also live reloading via spring-boot-devtools.

It would also ensure that we get the expected app to respond when doing client-side loadbalancing via Ribbon, for example.

**Comment by axelfontaine** [comment]
This is actually something we have been thinking about for a while as well.

As VirtualBox lacks first-class support for virtual ip addresses, we are currently thinking about doing this with the port forwarding. It would then look like this:

boxfuse run myapp:1
=> launches instance A and forwards localhost:1234 to instanceA:1234
=> Boxfuse performs the healthcheck against localhost:1234

boxfuse run myapp:2
=> launches instance B and forwards localhost:1235 (first available port) to instanceB:1234
=> performs the healthcheck against localhost:1235
=> terminates instanceA and removes the port forwarding for localhost:1234
=> forwards localhost:1234 (now free again) to instanceB:1234

Does this look good to you? Did we miss something important?

**Comment by herder** [comment]
Yes, that's about how I envisioned it, though the flow also has to handle separate values for server.port and management.port.

So I would like something like this flow (server.port is 1234, management.port is 1235):

boxfuse run myapp:1
=> launches instance A and forwards localhost:1234 to instanceA:1234
=> Boxfuse performs the healthcheck against localhost:1235

boxfuse run myapp:2
=> launches instance B and forwards localhost:1236 (first available port) to instanceB:1234 and localhost:1237 to instanceB: 1235
=> performs the healthcheck against localhost:1237
=> terminates instanceA and removes the port forwarding for localhost:1234
=> forwards localhost:1234 (now free again) to instanceB:1234
=> forwards localhost:1235 (now free again) to instancedB:1235
