### ISSUE TITLE
Allow environment and 'latest' alias for version

### ISSUE THREAD

**Issue by herder** [cloudcaptainsh/cloudcaptain#106]
A useful feature when deploying locally would be to allow specifying version via an environment name or `latest` for the latest version, like so:

`boxfuse run myapp:stage` - pulls the version of `myapp` which is deployed on stage an runs it in dev.
`boxfuse run myapp:latest` - retrieves the newest version of `myapp` and runs on dev.

This could also be used for pipeline functionality:

`boxfuse run myapp:stage -env=prod` - to deploy the stage version to prod.

**Comment by axelfontaine** [comment]
Hmm very interesting suggestion! We'll put some thought into this!
