### ISSUE TITLE
Option to leave previous instances of worker

### ISSUE THREAD

**Issue by herder** [cloudcaptainsh/cloudcaptain#109]
When deploying a worker app, the previous app version is killed without knowing if the app came up ok or not. Since this means that we can't know if a deploy went ok, I'd like to propose an option to leave the old ASG and kill it manually after inspection. 

Maybe something like `boxfuse run --no-kill-previous myapp`, which would start the new instances and leave the others running. Possibly also print a warning if we have more than two app versions running simultaneously?

**Comment by axelfontaine** [comment]
Actually you can have regular healthchecks today for your worker app. All you need to do is define either an http or https port where Boxfuse can perform the healthcheck.

**Comment by herder** [comment]
Aha, great! Missed that one :)

**Comment by herder** [comment]
Actually, it would be nice to be able to leave the old instances, even so - that would make visual inspection of the new instances a bit easier. But my immediate problem is fixed with the tip above :)

**Comment by herder** [comment]
And wouldn't inspecting the app config after a management.port, like the other app types, be a more consistent behaviour? I expected it to do that, but maybe there's some other problems with that approach?

**Comment by axelfontaine** [comment]
There is no difference in algorithm between app types for auto-detecting the healthcheck port.

**Comment by herder** [comment]
Weird... must be something in my config which causes it to skip the health
check.

tis 23 aug. 2016 kl 15:24 skrev Axel Fontaine <notifications@github.com>:

**Comment by axelfontaine** [comment]
Also note that in order for Boxfuse to be able to perform a healthcheck your instances must be within a VPC that assigns public IP addresses (otherwise we have no way to reach them)

**Comment by herder** [comment]
Ah, that's the reason, then. We are planning on moving our non-public services to an internal network, so that's why the healthcheck didn't kick in on our test app.

Would this be a valid use case for an option to disable tearing down of the old instances?
