### ISSUE TITLE
Set default logs.filter.start on logs.tail

### ISSUE THREAD

**Issue by herder** [cloudcaptainsh/cloudcaptain#150]
When using the logs.tail option, I would like the logs.filter.start option to be set to some reasonable value (-60, maybe), so that I don't have to wait for a few days' worth of older log entries before getting to the actual tail.

This should of course be overridden if I actually supply a logs.filter.start option.

**Comment by axelfontaine** [comment]
The default is indeed current to start from the beginning of the log retention.

You can however easily override this by placing `logs.filter.start=-60` in a boxfuse.conf file, either in the Boxfuse installation directory, the user home or the current directory (see https://boxfuse.com/docs/commandline/#overriding). When placed at the root of the project directory, this file can also easily be checked in and shared among team members.

Would that work for you?

**Comment by herder** [comment]
That would work, but in the spirit of 'sensible defaults' I'd like it to be preset by Boxfuse if I haven't specified anything myself. It's not uncommon to need to wait for over a minute or two to get to the tail (not that I wait that long: I kill the process and remember to add the logs.filter.tail option :) )
