### ISSUE TITLE
Error on NewRelic keys for EU servers 

### ISSUE THREAD

**Issue by sery0ga** [cloudcaptainsh/cloudcaptain#228]
Boxfuse makes a check for NewRelic key *ensure it is 40 chars long and only contains a-f (lowercase) and 0-9**. However, NewRelic keys for EU servers have a format **eu01xx[key]** failing a correct build with a correct key

**Comment by axelfontaine** [comment]
This has now been fixed in version `1.35.3.1526` of the client.
