### ISSUE TITLE
Multiple apps in same image

### ISSUE THREAD

**Issue by herder** [cloudcaptainsh/cloudcaptain#62]
I'd like to explore using sidecar apps à la Prana, to integrate Node apps with Eureka, Ribbon and the like.

Is that possible?

**Comment by axelfontaine** [comment]
Boxfuse images are regular Linux images (albeit incredibly lean) with a file system. For Node.js apps the npm-bundle tgz is unpacked in /app. You could therefore include a JRE and the Prana jars (from their lib directory) and invoke it on startup from your Node.js app.

Would that work for you?

**Comment by herder** [comment]
Yes, that would fit great! 
So if I have a Spring Boot app, I would build the jar as usual, then add the npm-bundle.tgz file and just do a normal `boxfuse run` ?

**Comment by axelfontaine** [comment]
If you want to have a Spring Boot app as a sidecar to a Node.js one, you should:

1. Build the Spring Boot jar
2. Include the Spring Boot jar and a Linux JRE in the directory structure of your Node.js app
3. Bundle up the directory structure of your Node.js app (containing the Node.js app, the Linux JRE and the Spring Boot app) into a tgz
4. Invoke "boxfuse run mynodeapp.tgz"
5. Have your Node.js app launch the JRE with the Spring Boot app on startup

Does that make sense?

**Comment by herder** [comment]
Aha, I see. Yeah, that would probably work. I'll try it out as soon as I get time.

**Comment by axelfontaine** [comment]
One more thing. Depending on what exactly you are trying to achieve it may be easier to just use the corresponsing npm module like this one for example: https://www.npmjs.com/package/eureka-js-client

**Comment by lizell** [comment]
I can confirm that this indeed works. I now have a node app happily running with a sidecar app in a bundled JVM.

@axelfontaine: It takes for ages to build and fuse so one thought would be to have an image with both JRE and Node available out of the box. Would that be possible?

**Comment by axelfontaine** [comment]
@lizell What type of fuse times are you seeing?

Note: As Boxfuse creates your images from scratch, there is no such concept of a base image with both the JVM and Node.js preinstalled.

**Comment by axelfontaine** [comment]
@lizell Please upgrade to 1.19.2.965 and compare the fuse times. We think you'll be pleasantly surprised :-)

**Comment by lizell** [comment]
Thanks. ;)

It takes 3-4 minutes to do the fusing for a payload of around 125MB.

I'm sorry I could not do any happy dances. Sure wanted too, but these are the results I got:

```bash
$ boxfuse -v
Boxfuse client v.1.18.7.938
Copyright 2016 Boxfuse GmbH. All rights reserved.

VirtualBox : 5.0.18r106667
JVM        : 1.8.0_74 (Oracle Corporation)
OS         : Mac OS X 10.11.4 x86_64

$ time boxfuse fuse
Image fused in 03:28.199s (124941 K) -> abcoreboxfuse/app:0.0.0.1463561555075boxfuse fuse  225,64s user 2,79s system 102% cpu 3:42,36 total
```
and after upgrade
```bash
Upgrade complete.

Boxfuse client v.1.19.3.966

$ time boxfuse fuse
Image fused in 03:15.384s (125152 K) -> abcoreboxfuse/app:0.0.0.1463567361866
boxfuse fuse  225,95s user 2,67s system 108% cpu 3:31,58 total

$ time boxfuse fuse
Image fused in 03:20.093s (125151 K) -> abcoreboxfuse/iris:0.0.0.1463567593695
boxfuse fuse  231,87s user 2,39s system 108% cpu 3:35,57 total
```
Maybe the change in fuse times was not that big betwen `1.18` and `1.19`?

**Comment by lizell** [comment]
> Note: As Boxfuse creates your images from scratch, there is no such concept of a base image with both the JVM and Node.js preinstalled.

OK, maybe it is my terminology. Sorry. I mean something like. Fuse me an image where I can run both node and jvm without having to bundle one of them in the payload. Does that make sense at all?

**Comment by axelfontaine** [comment]
@lizell Hmm that is incredibly high! In fact it is by far the highest we've ever seen! Our CI server regularly fuses images with payloads of a similar size in under 10 seconds! What type of hardware do you have (CPU & SSD speed)?

Thanks for clearing things up with the terminology, now I fully understand what you meant.

**Comment by lizell** [comment]
Sad to hear that. Could it be due the fact that `npm-bundle` creates **a lot** of files?
```bash
$ tar tvf payload.tgz | wc -l
   71133
```
Should I run the output with verbose and send you the log?

CPU: 2,7 GHz Intel Core i7
Memory: 6 GB 1600 MHz DDR3
SSD speed: Not sure, but here are the specs for the model: https://support.apple.com/kb/SP669?locale=en_US&viewlocale=en_US

**Comment by lizell** [comment]
I think the high fuse times started once the `-X` flag started output `Adding file entry: …`. Our have it always done that? I had to disable `-X` in our travis build because the log gets capped at 10 000 lines.

**Comment by axelfontaine** [comment]
Would you be able to share the sources of the application with us (we will treat them absolutely confidentially and delete them fully once done) so we could try and replicate the fuse times? (Needless to say we will not run your application anywhere, this is only to debug the fuse times) If you are OK with that, please get in touch at hello@boxfuse.com

**Comment by axelfontaine** [comment]
We just checked the history and the `Adding file entry` debug message was added in 1.19.0 and should therefore have had zero effect on the high fuse times with 1.18.7

**Comment by lizell** [comment]
Here is some more info from the travis logs:

```
Boxfuse client v.1.18.7.938
Image fused in 00:19.296s (98160 K)
```
and a couple of builds later
```
Boxfuse client v.1.19.1.952
Adding file entry: …
```
Aborted due to too many lines in output.

And then:
```
Boxfuse client v.1.19.1.952
Image fused in 01:49.283s (120949 K)
```

I will start to share the full log with you and see if I can reproduce it in a payload that does not contain any sensitive code.

**Comment by axelfontaine** [comment]
@lizell Thanks! Those times are very different from the ones you supplied before. Is this an apples-to-apples comparison? I am asking since the payload sizes seem different...

**Comment by lizell** [comment]
I leaning towards this being a number of files issue rather than a size issue. Just creating the tar takes 85s on my machine:
```bash
time tar zcf app-0.0.2.tgz package
tar zcf app-0.0.2.tgz package  12,69s user 6,81s system 22% cpu 1:25,95 total
```
I will send you this payload so you can try it out if you like.

**Comment by axelfontaine** [comment]
@lizell Yes that would be great as it would allow us to see where we could potentially optimize this.

**Comment by lizell** [comment]
> @lizell Thanks! Those times are very different from the ones you supplied before. Is this an apples-to-apples comparison? I am asking since the payload sizes seem different...

Nope, unfortunatelly not. And after looking into it more, It is probably due to adding a lot of small files in `node_modules` rather than the boxfuse client upgrade. You have the payload now if you want to test it yourself.

**Comment by lizell** [comment]
Ziping the same folder is a full minute faster:
```bash
time zip -q -r app-0.0.2.zip package
zip -q -r app-0.0.2.zip package  11,44s user 5,66s system 62% cpu 27,150 total
```

**Comment by lizell** [comment]
I can now confirm that the fusing times are back to normal, once I cleaned up the `node_modules`.

With around 4 000 files:
```bash
Image fused in 00:09.908s (100387 K) -> app:0.0.0.1463582851306
```
